### ISSUE TITLE
Public Admin page redirect

### ISSUE THREAD

**Issue by mnewberg1** [isovera/centralsquare#19]
It looks like there’s an odd redirect for the https://www.centralsquare.com/public-admin page. It’s pointing to http://superionstg.prod.acquia-sites.com/public-administration instead of pointing to https://www.centralsquare.com/public-administration.

Do we know why this is happening & can we fix this?

**Comment by nmangold** [comment]
A redirect existed at https://www.centralsquare.com/admin/config/search/redirect which I removed.
