### ISSUE TITLE
WordPress Files

### ISSUE THREAD

**Issue by mnewberg1** [isovera/centralsquare#20]
Do you have access to the media files from this page on our website? https://www.centralsquare.com/about-us
 
We need bios in a Word doc and .jpg headshots (300x300px) for our executive team members. They will be going in the virtual platform for our upcoming event and it would be great if I can get those files to use.

**Comment by nmangold** [comment]
@mnewberg1  https://www.centralsquare.com/admin/content?status=All&type=team_member&field_resource_type_target_id_verf=All&title=

**Comment by mnewberg1** [comment]
Thanks @nmangold! Sent image links & bios over to client- all is sorted out :')
